#!/bin/bash
#SBATCH --job-name=isoquant_sqanti_pipeline
#SBATCH --output=isoquant_sqanti_pipeline_%A_%a.out
#SBATCH --error=isoquant_sqanti_pipeline_%A_%a.err
#SBATCH --time=0-24:00:00  # adjust as needed
#SBATCH --mem=64G
#SBATCH --qos=short
#SBATCH --cpus-per-task=8
#SBATCH --array=0-9%10
#SBATCH --mail-type=BEGIN,END,FAIL
#SBATCH --mail-user=tianyuan.liu@csic.es

###############################################################################
# Script: isoquant_sqanti_analysis.sh
# Author: Auto-generated by AI assistant
# Description: Build transcriptomes for each LRGASP sample using IsoQuant
#              against (1) TUSCO annotation and (2) GENCODE reference, then
#              evaluate both assemblies with SQANTI3 using the reference GTF.
#              Inspired by flair_sqanti_analysis.sh
###############################################################################

# ------------------------ Configuration ------------------------------------ #
ISOQUANT_ENV="isoquant"            # name of conda env with IsoQuant installed
SQANTI3_ENV="SQANTI3.env"         # conda env containing SQANTI3
SQANTI3_PATH="${SQANTI3_PATH:-}"  # optional: directory containing sqanti3_qc.py (leave empty if in PATH)

BASE_DATA_DIR="/storage/gge/Tian/lrgasp_data"      # input FASTQ root
OUTPUT_BASE_DIR="/storage/gge/Tian/lrgasp_analysis/isoquant_sq3"  # out root

# Reference files – Human
HUMAN_GENOME="/storage/gge/Tian/lrgasp_data/reference/GRCh38.primary_assembly.genome.fa"
HUMAN_TUSCO_GTF="/storage/gge/Tian/lrgasp_data/reference/tusco_human_full.gtf"
HUMAN_REF_GTF="/storage/gge/Tian/lrgasp_data/reference/gencode.v47.annotation.gtf"

# Reference files – Mouse
MOUSE_GENOME="/storage/gge/Tian/lrgasp_data/reference/GRCm39.primary_assembly.genome.fa"
MOUSE_TUSCO_GTF="/storage/gge/Tian/lrgasp_data/reference/tusco_mouse_full.gtf"
MOUSE_REF_GTF="/storage/gge/Tian/lrgasp_data/reference/gencode.vM36.annotation.gtf"

THREADS=${SLURM_CPUS_PER_TASK}

# ----------------------- Helper functions ---------------------------------- #
source_conda() {
    echo "[INFO] Loading Anaconda module..."
    module load anaconda
    if [[ $? -ne 0 ]]; then
        echo "[ERROR] Could not load anaconda module."; exit 1;
    fi
    echo "[INFO] Anaconda module loaded."
}

activate_env() {
    local env_name=$1
    local exe_to_check=$2  # executable to check (optional)
    echo "[INFO] Activating conda environment: $env_name"
    conda activate "$env_name"
    if [[ $? -ne 0 ]]; then
        echo "[ERROR] Failed to activate $env_name environment."; exit 1;
    fi
    if [[ -n "$exe_to_check" ]]; then
        command -v "$exe_to_check" >/dev/null 2>&1 || { echo "[ERROR] $exe_to_check not found in PATH after activating $env_name"; exit 1; }
    fi
}

# ----------------------- IsoQuant runner ----------------------------------- #
run_isoquant() {
    local sample_dir_name=$1   # e.g. wtc11_cdna_ont
    local output_dir=$2        # novel_evl/sample or ref_evl/sample
    local gtf_file=$3          # TUSCO or REF annotation for guidance

    echo "[ISOQUANT] Starting for $sample_dir_name in $output_dir with gene DB: $(basename $gtf_file)" >&2
    mkdir -p "$output_dir"

    # Determine data_type based on sequencing platform keyword in directory name
    local data_type=""
    if [[ "$sample_dir_name" == *ont* ]]; then
        data_type="nanopore"
    elif [[ "$sample_dir_name" == *pacbio* ]]; then
        data_type="pacbio_ccs"
    else
        # try r2c2 counts as nanopore as well
        data_type="nanopore"
    fi

    # IsoQuant output prefix; will generate <prefix>.transcript_models.gtf etc.
    local prefix="$sample_dir_name"

    local models_gtf="$output_dir/${prefix}.transcript_models.gtf"

    if [[ -f "$models_gtf" ]]; then
        echo "[ISOQUANT] Skipping – output $models_gtf already exists" >&2
        echo "$models_gtf"
        return 0
    fi

    # Run IsoQuant
    echo "[ISOQUANT] Running isoquant.py --data_type $data_type" >&2

    isoquant.py \
        --reference "$GENOME_FASTA" \
        --genedb "$gtf_file" \
        --fastq "${READS_FOR_ISOQUANT[@]}" \
        --data_type "$data_type" \
        --threads "$THREADS" \
        -o "$output_dir" \
        -p "$prefix"

    if [[ $? -ne 0 ]]; then
        echo "[ERROR] IsoQuant failed for $sample_dir_name ($gtf_file)" >&2; exit 1;
    fi

    # Verify that transcript_models.gtf was produced
    if [[ ! -f "$models_gtf" ]]; then
        echo "[ERROR] Expected IsoQuant output $models_gtf not found." >&2; exit 1;
    fi
    echo "[ISOQUANT] Completed, produced $models_gtf" >&2
    echo "$models_gtf"  # return path
}

# ----------------------- SQANTI3 runner (reuse logic) ---------------------- #
run_sqanti3_qc() {
    local sample_dir_name=$1
    local output_dir=$2
    local isoforms_gtf=$3
    local ref_gtf=$4

    local sqanti3_output_dir="$output_dir/sqanti3_out"
    local sqanti3_out_prefix="${sample_dir_name}_sqanti"
    local sqanti3_result="${sqanti3_output_dir}/${sqanti3_out_prefix}_classification.txt"

    mkdir -p "$sqanti3_output_dir"

    if [[ -f "$sqanti3_result" ]]; then
        echo "[SQANTI3] Skipping – $sqanti3_result exists" >&2
        return 0
    fi

    echo "[SQANTI3] Running on $isoforms_gtf (sample $sample_dir_name)" >&2

    source_conda
    activate_env "$SQANTI3_ENV" "sqanti3_qc.py"

    local ref_genome_sqanti3="$GENOME_FASTA"

    if [[ "$GENOME_FASTA" == *.gz ]]; then
        local unzipped_genome_fasta="${OUTPUT_BASE_DIR}/reference/$(basename "$GENOME_FASTA" .gz)"
        mkdir -p "$(dirname "$unzipped_genome_fasta")"
        if [[ ! -f "$unzipped_genome_fasta" ]]; then
            echo "[SQANTI3] Unzipping genome for SQANTI3 to $unzipped_genome_fasta" >&2
            gunzip -c "$GENOME_FASTA" > "$unzipped_genome_fasta" || { echo "[ERROR] gunzip failed"; exit 1; }
        fi
        ref_genome_sqanti3="$unzipped_genome_fasta"
    fi

    local ref_gtf_sqanti3="$ref_gtf"
    if [[ "$ref_gtf" == *.gz ]]; then
        local unzipped_ref_gtf="${OUTPUT_BASE_DIR}/reference/$(basename "$ref_gtf" .gz)"
        mkdir -p "$(dirname "$unzipped_ref_gtf")"
        if [[ ! -f "$unzipped_ref_gtf" ]]; then
            echo "[SQANTI3] Unzipping annotation for SQANTI3 to $unzipped_ref_gtf" >&2
            gunzip -c "$ref_gtf" > "$unzipped_ref_gtf" || { echo "[ERROR] gunzip failed"; exit 1; }
        fi
        ref_gtf_sqanti3="$unzipped_ref_gtf"
    fi

    # sanity checks
    [[ -f "$isoforms_gtf" ]] || { echo "[ERROR] IsoQuant GTF $isoforms_gtf missing."; exit 1; }
    [[ -f "$ref_gtf_sqanti3" ]] || { echo "[ERROR] Reference GTF $ref_gtf_sqanti3 missing."; exit 1; }
    [[ -f "$ref_genome_sqanti3" ]] || { echo "[ERROR] Genome FASTA $ref_genome_sqanti3 missing."; exit 1; }

    "$SQANTI3_PATH/sqanti3_qc.py" \
        "$isoforms_gtf" \
        "$ref_gtf_sqanti3" \
        "$ref_genome_sqanti3" \
        -d "$sqanti3_output_dir" \
        -o "$sqanti3_out_prefix" \
        --skipORF \
        -t "$THREADS" \
        --report pdf || { echo "[ERROR] SQANTI3 failed"; exit 1; }

    echo "[SQANTI3] Completed $sqanti3_result" >&2
}

# ----------------------- Main script -------------------------------------- #

echo "================ IsoQuant + SQANTI3 Pipeline ======================"
echo "Date: $(date)"
echo "SLURM Job ID: $SLURM_JOB_ID   Array Task: $SLURM_ARRAY_TASK_ID of $SLURM_ARRAY_JOB_COUNT"

echo "[INFO] Creating output base directory $OUTPUT_BASE_DIR"
mkdir -p "$OUTPUT_BASE_DIR" || { echo "[ERROR] Cannot create $OUTPUT_BASE_DIR"; exit 1; }
cd "$OUTPUT_BASE_DIR" || { echo "[ERROR] cd failed"; exit 1; }

# ----------------------- Enumerate samples ---------------------------------
SAMPLE_DIRS=()
while IFS= read -r line; do
    SAMPLE_DIRS+=("$line")
done < <(ls -d ${BASE_DATA_DIR}/*/ | grep -v 'r2c2' | grep -v 'reference' | grep -v 'log' | grep -v 'illumina')

NUM_TOTAL_SAMPLES=${#SAMPLE_DIRS[@]}

echo "[INFO] Found $NUM_TOTAL_SAMPLES sample directories eligible for processing."

if [[ -z "$SLURM_ARRAY_TASK_ID" ]] || (( SLURM_ARRAY_TASK_ID >= NUM_TOTAL_SAMPLES )); then
    echo "[ERROR] Invalid or missing SLURM_ARRAY_TASK_ID ($SLURM_ARRAY_TASK_ID)"
    exit 1
fi

SAMPLE_PATH_FULL="${SAMPLE_DIRS[$SLURM_ARRAY_TASK_ID]}"
SAMPLE_DIR_NAME=$(basename "$SAMPLE_PATH_FULL")

echo "--------------------------------------------------"
echo "Processing sample: $SAMPLE_DIR_NAME (Task index $SLURM_ARRAY_TASK_ID)"
echo "--------------------------------------------------"

# Create output dirs for this sample
NOVEL_EVL_DIR="$OUTPUT_BASE_DIR/novel_evl/$SAMPLE_DIR_NAME"
REF_EVL_DIR="$OUTPUT_BASE_DIR/ref_evl/$SAMPLE_DIR_NAME"
mkdir -p "$NOVEL_EVL_DIR" "$REF_EVL_DIR"

# Detect species and choose references
if [[ "$SAMPLE_DIR_NAME" == es_* ]]; then
    SPECIES="mouse"
    GENOME_FASTA="$MOUSE_GENOME"
    TUSCO_GTF="$MOUSE_TUSCO_GTF"
    REF_GTF="$MOUSE_REF_GTF"
elif [[ "$SAMPLE_DIR_NAME" == wtc11_* ]]; then
    SPECIES="human"
    GENOME_FASTA="$HUMAN_GENOME"
    TUSCO_GTF="$HUMAN_TUSCO_GTF"
    REF_GTF="$HUMAN_REF_GTF"
else
    echo "[WARN] Cannot determine species from directory name $SAMPLE_DIR_NAME. Skipping."
    exit 0
fi

echo "[INFO] Species detected: $SPECIES"

# Ensure genome uncompressed for IsoQuant/minimap2 if needed
if [[ "$GENOME_FASTA" == *.gz ]]; then
    UNZIPPED_GENOME_FASTA="$OUTPUT_BASE_DIR/reference/$(basename "$GENOME_FASTA" .gz)"
    mkdir -p "$(dirname "$UNZIPPED_GENOME_FASTA")"
    if [[ ! -f "$UNZIPPED_GENOME_FASTA" ]]; then
        echo "[INFO] Decompressing genome FASTA to $UNZIPPED_GENOME_FASTA"
        gunzip -c "$GENOME_FASTA" > "$UNZIPPED_GENOME_FASTA" || { echo "[ERROR] gunzip failed"; exit 1; }
    fi
    GENOME_FASTA="$UNZIPPED_GENOME_FASTA"
fi

# Gather FASTQ files
FASTQ_FILES=($(find "$SAMPLE_PATH_FULL" -type f \( -name "*.fastq.gz" -o -name "*.fq.gz" -o -name "*.fastq" -o -name "*.fq" \)))
if [[ ${#FASTQ_FILES[@]} -eq 0 ]]; then
    echo "[ERROR] No FASTQ files found for $SAMPLE_DIR_NAME"; exit 1;
fi

echo "[INFO] Found ${#FASTQ_FILES[@]} FASTQ file(s) for sample."
for fq in "${FASTQ_FILES[@]}"; do echo "  - $fq"; done

# Store reads in global var for use in functions
READS_FOR_ISOQUANT=("${FASTQ_FILES[@]}")

# ----------------------- Activate IsoQuant env ---------------------------- #
source_conda
activate_env "$ISOQUANT_ENV" "isoquant.py"

# ----------------------- Run IsoQuant analyses ---------------------------- #

echo "================= IsoQuant with TUSCO (novel_evl) ================="
NOVEL_EVL_GTF=$(run_isoquant "$SAMPLE_DIR_NAME" "$NOVEL_EVL_DIR" "$TUSCO_GTF")

echo "================= IsoQuant with REF GTF (ref_evl) ================="
REF_EVL_GTF=$(run_isoquant "$SAMPLE_DIR_NAME" "$REF_EVL_DIR" "$REF_GTF")

# ----------------------- SQANTI3 QC -------------------------------------- #

echo "================= SQANTI3 QC on TUSCO assembly ===================="
run_sqanti3_qc "$SAMPLE_DIR_NAME" "$NOVEL_EVL_DIR" "$NOVEL_EVL_GTF" "$REF_GTF"

echo "================= SQANTI3 QC on REF assembly ======================"
run_sqanti3_qc "$SAMPLE_DIR_NAME" "$REF_EVL_DIR" "$REF_EVL_GTF" "$REF_GTF"

echo "--------------------------------------------------"
echo "Sample $SAMPLE_DIR_NAME completed at $(date)"
